"""
================================================================================
Validate Designed Antimicrobial Peptides (AMPs)
================================================================================

Purpose:
    This script evaluates peptides generated by a combination of a Conditional
    Variational Autoencoder (CVAE) trained on a large AMP database and a LSTM
    model trained on a smaller MIC dataset.

Main Steps:
    1. Load datasets:
        - generated peptides (designed_amps.fasta)
        - large AMP database (bigdatabase.fasta) → CVAE reference
        - small MIC dataset (micdatabase.fasta) → LSTM reference
    2. Extract features for each peptide:
        - Length
        - Net charge
        - Hydrophobicity
        - Amino acid composition
    3. Compute novelty for each peptide relative to the large AMP database
       using a sliding Hamming distance (CVAE novelty)
    4. Train a Random Forest classifier on the small MIC dataset using random
       shuffled sequences as negatives (LSTM activity predictor)
    5. Score each generated peptide:
        - CVAE novelty → emphasizes exploration/novelty (weight 90%)
        - LSTM predicted activity → minor contribution from MIC activity (weight 10%)
    6. Rank peptides by a weighted final score
    7. Compute global statistics and diversity
    8. Save results to a tab-delimited file (validation_results.txt)

Weighting Rationale:
    - CVAE (90%): Promotes novel sequences compared to the global AMP database.
    - LSTM/MIC (10%): Ensures some predicted antimicrobial activity based on
      experimentally validated MIC data.
    - The novelty score is normalized (~0-1) by dividing by ~10 to match the
      scale of the LSTM AMP score.

Usage:
    python3 validate_amps.py

================================================================================
"""
import numpy as np  # For numerical operations
from sklearn.ensemble import RandomForestClassifier  # For training the LSTM/MIC classifier
import random  # For generating random negatives (shuffling sequences)

# =========================
# FILES
# =========================
GENERATED_FILE = "designed_amps.fasta"  # Peptides generated by CVAE+LSTM
GLOBAL_DB = "bigdatabase.fasta"  # Large AMP dataset (CVAE reference)
MIC_DB = "micdatabase.fasta"  # Small MIC dataset (LSTM reference)

# =========================
# FASTA READER
# =========================
def read_fasta(file):
    seqs = []  # Store sequences
    seq = ""   # Temporary variable for each sequence
    with open(file) as f:
        for line in f:
            line = line.strip()  # Remove newline and spaces
            if not line:
                continue  # Skip empty lines
            if line.startswith(">"):  # Header line
                if seq:  # Save previous sequence
                    seqs.append(seq)
                    seq = ""
            else:
                seq += line  # Append line to current sequence
        if seq:  # Add last sequence
            seqs.append(seq)
    return seqs

# =========================
# FEATURES
# =========================
amino_acids = "ACDEFGHIKLMNPQRSTVWY"  # 20 standard amino acids

# Net charge calculation
def charge(seq):
    return seq.count('K') + seq.count('R') - seq.count('D') - seq.count('E')

# Fraction of hydrophobic residues
def hydrophobicity(seq):
    return sum(aa in "AILMFWV" for aa in seq) / len(seq)

# Amino acid composition (fraction of each aa)
def aa_composition(seq):
    return [seq.count(aa)/len(seq) for aa in amino_acids]

# Combine features for classifier
def extract_features(seq):
    length = len(seq)
    pos = seq.count('K') + seq.count('R')  # Positive residues
    neg = seq.count('D') + seq.count('E')  # Negative residues
    hydro = hydrophobicity(seq)
    # Features: length, pos, neg, net charge, hydro, aa composition
    return [length, pos, neg, pos-neg, hydro] + aa_composition(seq)

# =========================
# DISTANCE FUNCTIONS
# =========================
def hamming(a, b):
    return sum(x != y for x, y in zip(a, b))  # Simple mismatch count

def sliding_hamming(seq, target):
    min_dist = len(seq)  # Max possible distance
    for i in range(len(target) - len(seq) + 1):
        sub = target[i:i+len(seq)]
        dist = sum(a != b for a, b in zip(seq, sub))
        if dist < min_dist:
            min_dist = dist
    return min_dist  # Minimum distance of seq sliding along target

def min_distance(seq, dataset):
    # Find closest match of seq in dataset
    return min(sliding_hamming(seq, d) for d in dataset)

# =========================
# RANDOM NEGATIVES (for classifier training)
# =========================
def shuffled_peptide(seq):
    lst = list(seq)
    random.shuffle(lst)  # Shuffle residues
    return "".join(lst)

# =========================
# LOAD DATA
# =========================
dataset_global = read_fasta(GLOBAL_DB)  # CVAE reference
dataset_mic = read_fasta(MIC_DB)  # LSTM reference
peptides = read_fasta(GENERATED_FILE)  # Generated sequences

print(f"Generated peptides: {len(peptides)}")
print(f"Global AMP dataset: {len(dataset_global)}")
print(f"MIC dataset: {len(dataset_mic)}")

# =========================
# TRAIN CLASSIFIER (LSTM/MIC)
# =========================
negatives = [shuffled_peptide(seq) for seq in dataset_mic]  # Random negatives

X = [extract_features(seq) for seq in dataset_mic + negatives]  # Feature vectors
y = [1]*len(dataset_mic) + [0]*len(negatives)  # Labels: 1 = positive, 0 = negative

model = RandomForestClassifier(n_estimators=100, random_state=42)  # Train RF
model.fit(X, y)

# =========================
# ANALYSIS
# =========================
results = []

for p in peptides:
    novelty_global = min_distance(p, dataset_global)  # CVAE novelty (90% weight)
    amp_score = model.predict_proba([extract_features(p)])[0][1]  # LSTM/MIC score (10% weight)

    results.append({
        "seq": p,
        "charge": charge(p),
        "hydro": hydrophobicity(p),
        "nov_global": novelty_global,
        "amp_score": amp_score
    })

# =========================
# DIVERSITY
# =========================
distances = []
for i in range(len(peptides)):
    for j in range(i+1, len(peptides)):
        distances.append(hamming(peptides[i], peptides[j]))
diversity = np.mean(distances)  # Average pairwise Hamming distance

# =========================
# FINAL SCORE (CVAE 90%, LSTM 10%)
# =========================
def final_score(r):
    # Normalize novelty to ~0-1 by dividing by 10, then weight 0.9
    # LSTM score weighted 0.1
    return r["nov_global"] * 0.90 / 10 + r["amp_score"] * 0.10

results = sorted(results, key=final_score, reverse=True)  # Rank peptides

# =========================
# GLOBAL STATS
# =========================
charges = [r["charge"] for r in results]
hydros = [r["hydro"] for r in results]
nov_g = [r["nov_global"] for r in results]
scores = [r["amp_score"] for r in results]

print("\n=== GLOBAL STATISTICS ===")
print(f"Charge mean: {np.mean(charges):.2f}")
print(f"Hydrophobicity mean: {np.mean(hydros):.2f}")
print(f"Novelty (global) mean: {np.mean(nov_g):.2f}")
print(f"AMP score mean: {np.mean(scores):.2f}")
print(f"Diversity: {diversity:.2f}")

# =========================
# TOP PEPTIDES
# =========================
print("\n=== TOP 10 PEPTIDES ===")
for r in results[:10]:
    print(f"{r['seq']} | Final={final_score(r):.3f} | AMP={r['amp_score']:.3f} | C={r['charge']} | H={r['hydro']:.2f} | Ng={r['nov_global']}")

# =========================
# SAVE FILE
# =========================
with open("validation_results.txt", "w") as f:
    f.write("seq\tcharge\thydro\tnov_global\tamp_score\tfinal_score\n")
    for r in results:
        f.write(f"{r['seq']}\t{r['charge']}\t{r['hydro']:.3f}\t{r['nov_global']}\t{r['amp_score']:.3f}\t{final_score(r):.3f}\n")

print("\nSaved to validation_results.txt")
